name: Deploy chat app

on:
  push:
    branches:
      - master

jobs:
  clientBuild:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: test-chat-app
        run: npm ci

      - name: Lint code
        working-directory: test-chat-app
        run: npm run lint

      - name: Test code
        working-directory: test-chat-app
        run: npm test

      - name: Build app
        working-directory: test-chat-app
        run: npm run build
        env:
          REACT_APP_API_URL: 'https://chat-app-uygar-zain.azurewebsites.net/api'

      - name: Store build files
        uses: actions/upload-artifact@v2
        with:
          name: test-chat-app
          path: test-chat-app/public

  serverBuildAndDeploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    needs: clientBuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: test-chat-app
        run: npm ci

      - name: Lint code
        working-directory: test-chat-app
        run: npm run lint

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: chat-app-uygar-zain
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: test-chat-app

  clientDeploy:
    name: Deploy the app
    needs: serverBuildAndDeploy
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: test-chat-app
          path: test-chat-app/build

      - name: Deploy app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /test-chat-app/build
          skip_app_build: true